### PR TITLE
Update Mapbox SDK to version 11.3.0

### PR DESCRIPTION
**Pull request by wang-li**
A new major version of the Mapbox SDK is available.
This commit fixes the errors that rose after updating the SDK.
The offline workers for persisting the map offline were not used and have been deleted.

### CODE REVIEW

**Comment by nmondollot** [comment]
Do you think we should upgrade now or wait for the 11.x versions?

**Comment by wang-li** [comment]
@nmondollot Not sure to get what you mean, as this commit is the upgrade to the version 11.0.0 🤔

**Comment by nmondollot** [comment]
Usually `.0.0` releases can have little bugs that are fixed later on.
I'm wondering if we should wait a bit or not :)

**Comment by wang-li** [comment]
@nmondollot From the quick tests that I performed, it did not seem to be unstable, but it is not a super urgent update on the other hand. Maybe we can wait to see if it is as stable on iOS, so that we upgrade Mapbox on both platforms at the same time

**Comment by nmondollot** [comment]
11.2 is out
should we make the upgrade in the next release? (after the one you're about to do with the tick filter)

**Comment by wang-li** [comment]
Yes, let's make the update after the next release, I think there are enough things to be shipped between the completion of the filters bar and the dark mode 👍

**Comment by wang-li** [comment]
@nmondollot I added the bearing indication on the user's position, as requested by the user who sent us an email ✌️

**Comment by nmondollot** [comment]
Ah, I thought it was already there!
Great that it's finally the case, it's very helpful to find your way around in the forest 👍 

Regarding the release: did you see any new behaviors with the new major mapbox version? some things I should test?

**Comment by wang-li** [comment]
> did you see any new behaviors with the new major mapbox version? some things I should test?

@nmondollot So far, I did not spot any behavior changes when using the app, not sure that you should have any particular test to perform. I just had to adapt the code to the new API from MapBox.

**Pull request merged**
