### PR TITLE
Add discover tab

### PR DESCRIPTION
**Pull request by wang-li**
The discover tab was not implemented in the android app, but already available in the iOS one.
This commit adds the tabs in the app, along with all the newly accessible screens:
* Discover
* Levels
* Beginner levels
* Areas that dry fast
* Areas accessible by train and bike

https://github.com/boolder-org/boolder-android/assets/8343416/fdd5222d-0191-4488-bcf2-f9561bd885a0

### CODE REVIEW

**Review by nmondollot — APPROVED** [review]
Works great 🤩

**Comment by nmondollot** [comment]
One thing we could improve: when the user goes on the discover tab, taps on an area and then taps on "see map", they're redirected to the map tab, but the position inside the discover tab is lost when they go back to the tab => a bit annoying

And also, I still have several "area not detected" and "wrong area detected" issues as explained [here](https://github.com/boolder-org/boolder-android/issues/68)
Not a blocker to ship the new tab of course, but it should be high on our todo list in my opinion.

**Comment by wang-li** [comment]
@nmondollot When activating the multiple back stacks with the navigation components library, the previous destination in the discover tab is properly restored, but the item selection in the bottom bar is not... According to the documentation, it should be working out of the box, but I ignore why this bug happens 😬 The selection in the bottom bar will happen only when the discovery fragment is displayed again.

https://github.com/boolder-org/boolder-android/assets/8343416/44196da9-48bc-411c-85a1-709316aae6cf

Also, having the tabs always displayed can lead to situations where both tabs display the same fragment:

https://github.com/boolder-org/boolder-android/assets/8343416/ab8518a2-a5dd-47b6-ba1b-eb989a711a0e

For these reasons, even if it might be annoying to not keep the last destination in the discover tab, I propose to keep the current behavior.

About the area detector bug, no code has been edited in a way to solve it in this PR, as it is a different scope, but I agree that it should be solved soon 👍

**Comment by nmondollot** [comment]
All right!

**Pull request merged**
