### PR TITLE
Implement circuit filter

### LINKED ISSUE #27: Circuit filter
Allow users to filter by circuit (of the currently selected area)

Pre-requisites: #25 and #26

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/59224e43-70f1-4c58-afa4-e67f52341721

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/main/Boolder/UI/Map/CircuitPickerView.swift

https://github.com/boolder-org/boolder-ios/blob/main/Boolder/UI/Map/AreaToolbarView.swift#L83-L112

https://github.com/boolder-org/boolder-ios/blob/main/Boolder/UI/Map/AreaToolbarView.swift#L240-L263

https://github.com/boolder-org/boolder-ios/blob/69421526647b93d06ec036c354492578678d053d/Boolder/Models/Area.swift#L185-L204 => see how we select only circuits that have a least [10 problems](https://github.com/boolder-org/boolder-ios/blob/69421526647b93d06ec036c354492578678d053d/Boolder/Models/Area.swift#L191) in the given area

### PR DESCRIPTION
**Pull request by wang-li**
The circuit filter button was missing in the android app.

In order to provide the same user experience as in the iOS app, the boulder problem grades filter button has been moved to the top of the screen, right under the search bar / area bar.

As this part is written in compose, the logic needed to conform to the unidirectional data flow principle, which implied a bit of changes about the screen state's structure.

https://github.com/boolder-org/boolder-android/assets/8343416/24fafac2-8261-410a-af38-c5dadd5478c5

Resolves #27

### CODE REVIEW

**Comment by nmondollot** [comment]
Wow 🤩 
I've been waiting for this for so long! 
So great :)))

Here are a few things I have in mind to polish the experience.
We can discuss them tomorrow!

## Make the circuit problems bigger

When the circuit filter is activated, let's increase the size of circuit problems

2 reasons:
- the user can see the circuit numbers even when zoom is low
- if there are multiple problems that are close together, the circuit problem will have the priority when the user taps on it (or close to it), which makes sense when we're in circuit mode

| Android | iOS |
|--------|--------|
| Screenshot_20231025_124133_Boolder | IMG_20DAC246A5F5-1 |

FYI on iOS I used a [dedicated mapbox layer](https://github.com/boolder-org/boolder-ios/blob/05ebdc6d294f1041e566fcded18e9def4509aeec/Boolder/UI/Map/MapboxViewController.swift#L292-L352) for this.

## Mutually excluding filters

In the iOS app, I use mutually excluding filters.
Meaning that when the user selects a circuit filter and *then* selects a level filter, I discard the circuit filter automatically.
Same thing the other way around: I discard the level filter when the user selects a circuit filter.

The reason behind this is that it's very rare to want to use both filters at the same time
And it's annoying to discard the filter yourself (you have to go to the filter and tap on "clear").

What do you think?

## More map screen estate

When the bottom sheet is displayed, we can hide the filters bar to give the user more space to use the map.
It's especially useful on small screens.

FYI we do the same on iOS.

## Don't lose filters when zooming out

When I zoom out of an area, I lose the circuit filter (but not the level filter) => it's not consistent

I think we should keep the circuit filter.

Bug that is probably related: when I go to Isatis and select the red circuit, the circuit filter is immediately discarded :(


## Other fixes

- I can't tap on the compass view anymore, it's probably hidden by the new filters bar
- circuit label: "Circuit Blue" -> "Circuit Bleu" 
- when there is no circuit (e.g. Cuvier Bellevue) we should maybe change the label (to "No circuit"?). FYI on iOS I hide the circuit button, but it creates other problems so I'm not sure it's the perfect solution.


## Hit next multiple times

(not a big priority, but nice to have)

Let's say I'm at problem number 1 and I want to quickly go to problem number 5.
One way to do it is to tap 4 times on the next button.

Currently, when there is a problem with no steepness or sit_start the bottom sheet's height changes, which makes the button vertical position change too => I mistap the next button and I close the bottom sheet inadvertently 

Possible solution: keep the bottom sheet height fixed.
(FYI on iOS I add a blank space at the bottom of the sheet)

**Comment by nmondollot** [comment]
> Make the circuit problems bigger
> A new layer has been added like in the iOS app

👍 

One issue though: when I tap on a (big) circuit problem I often select another problem by mistake.
Did you make this new layer tappable? 

> Mutually excluding filters 
> I opted for a reset button proposal instead, keeping the ability to combine the filters. Tell me if you think that it fits the use case.

I actually really like it! Great job
I will probably do the same on iOS :)

The only problem I have is that I find the reset icon not super clear. Is it standard on Android?
In my opinion it would be clearer to have an icon related to "clear" (a cross?), and maybe even a label saying "clear" (or "clear filters")

> More map screen estate
> The filters bar fades out when the topo bottom sheet is expanded, and fades in when it is dismissed with a zoom level that is high enough to display the problems

👍 

> Don't lose filters when zooming out
> This will be a headache to manage, as the circuit filter is availability is based on the area detector's value. When zooming out, the area detector becomes inactive, clearing the circuit filter.

Ok no big deal, I understand.

> ❓ An empty state is now displayed, is it ok for you?

Yes!


## Other feedback

- on iOS I hide the "départ circuit" button as soon as the user moves the map, to avoid distracting them for too long. What do you think?

**Comment by wang-li** [comment]
> One issue though: when I tap on a (big) circuit problem I often select another problem by mistake.
Did you make this new layer tappable?

Good catch, I actually totally missed this part! 👍 

> The only problem I have is that I find the reset icon not super clear. Is it standard on Android?
In my opinion it would be clearer to have an icon related to "clear" (a cross?), and maybe even a label saying "clear" (or "clear filters")

Nope, it was not a standard icon from Android, but I thought it was showing the "reset" action correctly 😅 I changed it for the material design's "cancel" icon, is it ok for you? I do not think that a label should be added, so that it does not look like a kind of filter (as it is a special action) and takes less space in the filters bar. Or maybe it can show up in a different color.




> on iOS I hide the "départ circuit" button as soon as the user moves the map, to avoid distracting them for too long. What do you think?

I chose to hide this button when a topo is shown instead, so that the user will still have the possibility to go to the circuit start if he/she pans on the map. I assume that tapping a problem on the map means that they are not interested in going to the circuit start. What do you think about that alternative?

**Comment by nmondollot** [comment]
Looking good! 🤩 

> Nope, it was not a standard icon from Android, but I thought it was showing the "reset" action correctly 😅 I changed it for the material design's "cancel" icon, is it ok for you?

Ok 👍 

> I chose to hide this button when a topo is shown instead, so that the user will still have the possibility to go to the circuit start if he/she pans on the map. I assume that tapping a problem on the map means that they are not interested in going to the circuit start. What do you think about that alternative?

Ok, good call

**Review by nmondollot — APPROVED** [review]
Ok to merge!
I'll open a separate issue for Isatis's red circuit though.

**Pull request merged**
