### PR TITLE
Area bar adjustments

### LINKED ISSUE #37: Area bar (basic)
Now that we have an [area detector](https://github.com/boolder-org/boolder-android/pull/36#event-10389681039), let's build a basic UI when an area is selected.

Behavior:
- the area bar displays the area's name, but isn't tappable (yet)
- the area bar replaces the search bar when an area is selected
- there is a back button to go back to search
- the area bar is hidden when `zoom < 15` 

Note: we'll implement filters in [v2](https://github.com/boolder-org/boolder-android/issues/38)

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/3cfebce6-e62d-4671-8eea-d90f1f8b206c

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/AreaToolbarView.swift

### PR DESCRIPTION
**Pull request by wang-li**
According to #37 the area bar should be positioned on the search bar.

https://github.com/boolder-org/boolder-android/assets/8343416/ee7c8c7c-8714-4a13-9372-1fa0b9cffbe0

The zoom threshold of `15` was out of sync with the map content change, so I kept it to `14.5`. Just tell me if you think the threshold value should be synced to `15` instead of `14.5`.

Resolves #37

### CODE REVIEW

**Comment by nmondollot** [comment]
Great! 🥳 

A few things:

1/ The search doesn't seem to work anymore 🤕 

2/ Can you use a slightly larger font size for the area's name? Maybe the same as the search placeholder to stay consistent?

3/ Small bug: when mapbox data isn't loaded yet (eg: at first start) and I tap on an area's hull, the area detector doesn't work

https://github.com/boolder-org/boolder-android/assets/330823/b8283e25-fc4b-4556-9da9-2680544f4a11

Possible solution: set the area manually when user taps on an area

Note: same thing when :
- user selects an area from the search
- (in the future) user selects an area from the discover tab

**Comment by nmondollot** [comment]
> The zoom threshold of 15 was out of sync with the map content change, so I kept it to 14.5. Just tell me if you think the threshold value should be synced to 15 instead of 14.5.

Ok let's keep 14.5 👍

**Comment by wang-li** [comment]
> 1/ The search doesn't seem to work anymore 🤕

Oops my bad, I was too focused on testing the display on the area itself 😅 

> 2/ Can you use a slightly larger font size for the area's name? Maybe the same as the search placeholder to stay consistent?

This should be consistent now. I also set the text to a single line with an ellipsis if it gets too long 

> 3/ Small bug: when mapbox data isn't loaded yet (eg: at first start) and I tap on an area's hull, the area detector doesn't work

This one along with the search should be fixed, as the area name display is triggered by the end of the camera animation. I had to add an animation after selecting an area in the search to make it work

Here is the result on my OnePlus One:

https://github.com/boolder-org/boolder-android/assets/8343416/580f824e-0eff-400b-b63b-9c512ccd10b8

**Comment by nmondollot** [comment]
Great!

One last thing I noticed: the small bug still happens when I do a search and tap on a **problem** in the list
(i.e. the area name doesn't appear when the map data isn't loaded yet)

Other than that you can go ahead and merge 🚀 
I'll probably do a release early next week.

**Comment by wang-li** [comment]
@nmondollot I added a camera animation on problem selection, coupled to an animation listener that will make the area name being display when selecting a problem from the search 😉

**Pull request merged**
