### PR TITLE
Implement circuit mode

### LINKED ISSUE #26: Circuit mode
Add previous/next arrows when a problem belongs to a circuit.
When user taps on an arrow, display the circuit's path (and a way to dismiss it)

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/e377cf47-6add-4efd-bbba-7c3326528ea0

https://github.com/boolder-org/boolder-android/assets/330823/f92215e9-b7f2-42a4-9309-4a664e7026a4

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/MapboxViewController.swift#L292-L352

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/MapboxViewController.swift#L780-L809

### PR DESCRIPTION
**Pull request by wang-li**
The circuit mode was missing in the android app. This commit adds it.

https://github.com/boolder-org/boolder-android/assets/8343416/ac4b168b-7284-4588-a48d-99c562170080

Side note: the Mapbox SDK has been updated to the latest version.

Resolves #26

### CODE REVIEW

**Comment by nmondollot** [comment]
🤩 

This one is going to make a lot of people happy!

My feedback:
- previous/next buttons: can you use the circuit's color for the arrow? it's more immersive. (you can use black for the white circuit)
- if the user selects a problem on a topo, it should trigger circuit mode the same way as when the user selects it from the map

Other than that it works great!
We can discuss some small details (like whether to display the circuit path right away or not) when you implement the circuit filter.
(one other example: there is currently no way to see the circuit path when the bottom sheet is dismissed)

**Comment by nmondollot** [comment]
Great!
Can't wait to ship this one :)

One small bug: the pan/zoom is changed when i tap on a problem now
I preferred the old behavior when the map stayed the same.

**Comment by wang-li** [comment]
> One small bug: the pan/zoom is changed when i tap on a problem now
I preferred the old behavior when the map stayed the same.

I pushed one more commit to fix this behavior, is it matching your expectation?

**Comment by nmondollot** [comment]
Yes, better 👍 

However you still keep re-centering the map when the user taps on a problem.

On the one hand I like it because it makes the problem centered.
On the other hand I think it may be annoying when the user wants to go back and forth between several problems.

See how they handle it on Google Maps:

https://github.com/boolder-org/boolder-android/assets/330823/2ade5b40-f1ee-4a7a-bb71-5fcc2f06a38a

They center the map only when the pin is (almost) hidden by the bottom sheet.
But the rest of the time the map stays in the same place.

What do you think?

On the iPhone app I do the same as Google Maps, but I'm open to new ideas and I can update the behavior on iPhone if needed.
The important thing is that we have the same UX as possible between the two.

**Comment by wang-li** [comment]
> On the one hand I like it because it makes the problem centered.
On the other hand I think it may be annoying when the user wants to go back and forth between several problems.

In my opinion, it is more consistent to always center on the selected problem, as this is what is done after a search, or a navigation on the same circuit. It will also make the code a bit less complicated.

I adjusted the centering of the selected boulder problem to be closer to the Google Maps' behavior in the last commit, but I did not really find an elegant way to handle the close-to-screen-edge boulder problems.

The boulder problem will be centered only if its display event comes from a search validation, or a circuit navigation, and never in the other cases, as shown in the following recording:

https://github.com/boolder-org/boolder-android/assets/8343416/a7e85f6f-d3ee-4f87-9d15-53012224d893

**Comment by nmondollot** [comment]
Great! I like it 👍 

I let you merge the branch and then I'll do a new release :)

**Review by nmondollot — APPROVED** [review]

**Pull request merged**
