### PR TITLE
Implement the area detector

### LINKED ISSUE #25: Area detector
We want to be able to detect in which area the user is currently looking at on the map.
This will be useful for a number of features (example: show more info about the area, show the list of the area's circuits, ...)

To do so, we draw an (invisible) square in the middle of the screen, and we check if it collides with an area's hull (= the shape of the area on the map, shown in grey to the users).

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/1eb1c6a9-a300-4ba6-b96d-9a3f454af502

Notice how the top bar shows "Cuvier" and then "Cuvier Ouest" just by moving the map

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/MapboxViewController.swift#L593-L632

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/MapboxViewController.swift#L60-L74

### PR DESCRIPTION
**Pull request by wang-li**
In order to provide information to the user about the displayed area on the map, an area detector needs to be implemented first. 

https://github.com/boolder-org/boolder-android/assets/8343416/471c9329-80a0-4f3f-a8cc-2f51d37898d8

This commit also updates the libs that are used in the project.

Resolves #25

### CODE REVIEW

**Comment by nmondollot** [comment]
Awesome!

It's a great milestone towards https://github.com/boolder-org/boolder-android/issues/27 :)

Small question: are performances ok even on slower devices?

**Comment by wang-li** [comment]
> Small question: are performances ok even on slower devices?

The oldest device that I have is a OnePlus One, and here is how it looks:

https://github.com/boolder-org/boolder-android/assets/8343416/92209abe-1bd0-4267-8030-5d1ed7e7c3fc

I think it is good enough performance wise 😄

**Comment by nmondollot** [comment]
One last thing: the white bar with the area's name looks a bit weird => can you remove it (for now)?

I'll open a new issue to clarify the specs of the top bar when an area is selected

Thanks!

**Comment by nmondollot** [comment]
Here it is: https://github.com/boolder-org/boolder-android/issues/37

**Comment by wang-li** [comment]
> One last thing: the white bar with the area's name looks a bit weird => can you remove it (for now)?

As this PR was already merged, I directly implemented the specs from #37 in another PR #40

**Pull request merged**
