### PR TITLE
Display warning icon in area bar

### LINKED ISSUE #103: Warning inside area bar
We want users to be more aware of area warnings (example: reserve de chasse, poor connectivity) when they are on the map.

Solution: when an area has a warning text, display a warning icon inside the area bar.

### PR DESCRIPTION
**Pull request by wang-li**
We want users to be more aware of area warnings (example: hunting reserve, poor connectivity) when they are on the map.

Also, in the case of a poor connectivity, we want to make the area photos download button more visible.

|Before|After|
|-|-|
|||
|||
|||

Resolves #103

### CODE REVIEW

**Comment by nmondollot** [comment]
It really catches the attention, that's good 👍 

However I realize that some (actually most) warnings don't really require to catch the attention from the map screen.

Here's the current list:

| area | warning_fr |
|--------|--------|
| Coquibus Rumont | Réserve biologique : évitez de pénétrer dans les sous-bois et tenez votre chien en laisse d’avril à juillet.|
| Roche aux Oiseaux | Février 2022 : le circuit orange est complètement effacé.|
| La Reconnaissance | Il est difficile de se déplacer et de se repérer dans ce secteur.|
| Dame Jouanne | Attention : les blocs sont en moyenne (très) hauts et ne conviennent pas aux débutants. À savoir : Il est difficile de se repérer dans le chaos rocheux, notamment avec les peintures qui sont pour la plupart effacées. Plusieurs zones sont également fermées à cause de l'érosion du sol.|
| Haute Pierre | Réserve de chasse : ne pas y grimper pendant la période de chasse : mi-septembre à premier mars.|
| J.A. Martin | Juin 2022 : certaines peintures sont effacées, le topo ou l'appli sont vivement recommandés.|
| Éléphant | Attention, les blocs sont en moyenne (très) hauts ! 2018 : le bloc de l'Éléphant est interdit à la grimpe à cause d'un risque d'éboulement.|
| Gorge aux Châts | Le parking le long de la route des Grandes Vallées n'est plus accessible.|
| Rocher des Demoiselles | Mai 2022 : le circuit orange est presque complètement effacé.|
| Apremont Solitude | Octobre 2022 : La peinture du circuit rouge est très effacée, il est difficile de se repérer.|
| Rocher d'Avon | Septembre 2022 : le parking historique le long de la D606 n'est plus accessible.|
| Cuvier Rempart | Attention : le circuit jaune ne convient pas du tout aux débutants.|
| Apremont Est | À savoir : il est assez difficile de se déplacer et se repérer, le secteur étant situé dans un vrai chaos rocheux.|
| Rocher d'Avon Est | Septembre 2022 : le parking historique le long de la D606 n'est plus accessible.|

The only warnings worth displaying a warning badge are the ones about "reserve biologique" and "reserve de chasse".
We should maybe add a boolean to differentiate these cases, what do you think?

Regarding the "poor connectivity" case, I could easily add a warning text for the concerned areas (cuvier etc)
However I'm wondering if it's a good idea to *always* display the warning from the map 🤔 
Maybe there should be a way for the user to dismiss the warning when they have 1/ downloaded the area photos, or 2/ tapped on a dismiss button

What do you think?

**Comment by wang-li** [comment]
Well, I would say that if the message is not a warning that really deserves attention, it should not be mentioned as a warning 😅 
So I would better be in favor of simplicity and keeping only one level of warning, either having all the current warnings on the same line, or integrating the "low warnings" to the description of the area.

> Regarding the "poor connectivity" case, I could easily add a warning text for the concerned areas (cuvier etc)
However I'm wondering if it's a good idea to always display the warning from the map 🤔
Maybe there should be a way for the user to dismiss the warning when they have 1/ downloaded the area photos, or 2/ tapped on a dismiss button

To me, it is more the kind of behavior that we would want if we were displaying an "invasive" message, like a dialog. Currently, the warning icon is just figurative (and not meant to be dismissed in any way, otherwise users might try to dismiss it for all the other cases as well), so that users who intent to go to the area will avoid missing the warning when using the app.

**Comment by nmondollot** [comment]
> Well, I would say that if the message is not a warning that really deserves attention, it should not be mentioned as a warning 😅

Haha good point :)
I guess we could keep the warnings only for the "special access" cases (hunting area, biological reserve, integral biological reserve, private property, ...)
And move the other warnings to the `description` field.
If you're ok I can make the modifications in the admin and do a new boolder-data release.

And what about adding the same icon next to the warning text?
It would make it easier for the user to understand that the warning icon on the map is related to the warning text on the area screen.

> To me, it is more the kind of behavior that we would want if we were displaying an "invasive" message, like a dialog. Currently, the warning icon is just figurative (and not meant to be dismissed in any way, otherwise users might try to dismiss it for all the other cases as well), so that users who intent to go to the area will avoid missing the warning when using the app.

Yeah, allowing to dismiss the icon may not be what we want.
However I find the warning icon distracting and UGLY 😅 so I'm really not ok showing it all the time for popular areas like Cuvier.
I'm sure we can find a better solution.

What about displaying a tooltip that shows up only once? We could try a few different rules as to when/where it shows up to avoid distracting users too much. Let's do that in a separate issue.
We'll probably want to have more qualitative & quantitative feedback to choose the best solution though.

**Comment by nmondollot** [comment]
> Alright, keep me updated 👍

Ok, I will do it today or tomorrow

> This can be done, it's not a huge deal 😉

Ok let's do it!

> Would you prefer to simply have an orange dot in the top right corner of the info button? This will be a bit less distracting but also emphase less about the warning nature of its presence.

No, I prefer to have a very visible warning icon when it's needed (hunting reserve, etc) and no warning at all for other cases

FYI this is how bleau.info show a big warning on their area page:

Capture d’écran 2024-04-30 à 16 10 01

> The problem with a tooltip is that once displayed and dismissed, it will not reappear for a while, which can be problematic for warnings such as the hunting one

I suggested to use a tooltip only for the poor connectivity case.
But let's keep that for a separate issue (probably after our boolder weekend, when we have more feedback on how people use it).

**Comment by wang-li** [comment]
> Ok let's do it!

Done ✅ Here is the result:



> I suggested to use a tooltip only for the poor connectivity case.
But let's keep that for a separate issue (probably after our boolder weekend, when we have more feedback on how people use it).

Alright, let's keep it on the side for now

**Comment by nmondollot** [comment]
the new warnings are available:
https://github.com/boolder-org/boolder-data/releases/tag/v1.3.11

**Comment by wang-li** [comment]
> the new warnings are available:
https://github.com/boolder-org/boolder-data/releases/tag/v1.3.11

Alright, I will update it in a separate PR 👍  #105

**Pull request merged**
