### PR TITLE
Implement tick list tab

### LINKED ISSUE #28: Tick list
- Allow users to mark a problem as "ticked" or as a "favorite".
- Add a tab in the app to display the list of ticks and favorites (and tap on a problem to see it on the map)

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/b5ef131f-6b0b-47eb-b4f9-ef38f7a59c3f

https://github.com/boolder-org/boolder-android/assets/330823/b5d59f58-7bda-4a6e-8db6-8a2e0fd53dfb

# Data model

Let's store the data locally on disk (on iOS we use a separate sqlite database via CoreData) with the following schema:

Ticks:
- `id` (optional)
- `problemId`
- `createdAt`

Favorites:
- `id` (optional)
- `problemId`
- `createdAt`

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Tick%20List/TickList.swift

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/Problem%20details/ProblemDetailsView.swift#L199-L219

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/Problem%20details/ProblemDetailsView.swift#L277-L364

### PR DESCRIPTION
**Pull request by wang-li**
The tick list tab was implemented in the iOS app but missing in the android one.
This commit implements that tab, along with the ability to add a problem as ticked or as a project.

https://github.com/boolder-org/boolder-android/assets/8343416/f140edbe-388b-4562-abff-8b4a35599dad

The ticks are stored in a separate database meant to contain the user's data.

Resolves #28

### CODE REVIEW

**Comment by nmondollot** [comment]
Works great!!
Excellent job 👏 

Only small improvement I see:
- there is small horizontal padding for the bottom sheet buttons (bleau.info, enregistrer, partager) => it would look better if there was no padding at the start/end of the scrollview, so that we have the feeling that the buttons disappear beyond the edges of the screen

Other questions I have:
- in the new tab, how is the list scroll performance with lots of ticks (let's say a few hundreds)? 
- what happens if the user deletes/uninstalls the app? do they lose their ticks?
- what happens if a user ticks a problem, and the problem_id doesn't exist anymore after a boolder.db update?
- can we easily add/remove fields in the future?

**Comment by wang-li** [comment]
The padding on the topo actions is fixed ✅ :


<br /><br />

> in the new tab, how is the list scroll performance with lots of ticks (let's say a few hundreds)?

The list scroll performance should not be an issue, as the whole content is computed at once. I performed a test on my OnePlus 5T with 3000 problems being marked as project and here is the result:

https://github.com/boolder-org/boolder-android/assets/8343416/e29d6eda-7b4a-424f-a3c5-db2c6c4f56df

The only drawback is that the initial computing is a bit long, but the scrolling is alright. The subsequent displays of the list will be faster after this first computing.

> what happens if the user deletes/uninstalls the app? do they lose their ticks?

The deletion of the app will also delete the associated databases and lose the user's ticks. I took a look at the [auto backup feature](https://developer.android.com/guide/topics/data/autobackup) but it seems that it does not work directly with database files and the limit is 25MB per user. Therefore, I assumed that the future synchronization of the ticks in a Boolder profile would be more practical for this purpose.

> what happens if a user ticks a problem, and the problem_id doesn't exist anymore after a boolder.db update?

The ticked problem will simply not appear anymore in the tick list screen. A `mapNotNull()` is performed when trying to link to problem info to a tick, which equivalent to `compactMap()` in Swift.

> can we easily add/remove fields in the future?

As the ticks are stored in a SQLite database, migrations have to be written when changing the database schema in order to keep the user's ticks. Not the easiest or most seamless, but still reasonably doable.

**Comment by nmondollot** [comment]
Great! Let's ship it 😎 

One last thing: 
- bottom sheet: when the second row (like "wall / sit start") is empty we can't see the tick/favorite icon

**Review by nmondollot — APPROVED** [review]

**Comment by wang-li** [comment]
> bottom sheet: when the second row (like "wall / sit start") is empty we can't see the tick/favorite icon

Fixed, here are the various situation for the topo footer:
| | Marked as project | Ticked |
|-|-|-|
||||
||||

**Pull request merged**
