### PR TITLE
Implement boulder problem variants

### LINKED ISSUE #20: Variants
Display a button to see the list of variants of a problem.
When the user taps on a variant name, go to the variant.

# What is a variant?

A variant is a problem that is very similar to an existing problem but has a slight difference (sit start, line going slightly left or right, forbidden hold, ...).

A problem can have zero, one, or multiple variants.
One problem is considered as the **parent** problem, and the other problems as **children**, using the `parent_id` column of the `problems` table (see https://github.com/boolder-org/boolder-data for more info).
Note: to make it simpler, a child cannot have another child.

When showing variants of a problem, we don't care about who is parent and who is child, we just want to show all the variants of the same "family".

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/bc7f23b6-437a-484c-815c-20c7da1f4c54

# iOS code

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/Problem%20details/ProblemDetailsView.swift#L221-L251

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/Models/Problem.swift#L67-L78

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/Models/Problem.swift#L225-L244

### PR DESCRIPTION
**Pull request by wang-li**
Some boulder problems have variants, but they were not displayed on the topo's bottom sheet. This commit adds a variant selector in the upper right corner of the topo's bottom sheet.

https://github.com/boolder-org/boolder-android/assets/8343416/613e1890-3ffc-4ca8-a7b2-68860aef6dea

The design of the variant menu follows the material design implementation, I just added a rounded background around the variant's grade to make it more visually appealing.

Resolves #20

### CODE REVIEW

**Comment by nmondollot** [comment]
You rock!

> The design of the variant menu follows the material design implementation, I just added a rounded background around the variant's grade to make it more visually appealing.

You're right, the grade can be made more visible.
However the rounded black background make it seem like it belongs to a black circuit => It's a bit confusing in my opinion.
Is there a way to highlight the grade more subtly? For example we could align the grade on the right side (and keep the problem name on the left side).
What do you think?

**Comment by nmondollot** [comment]
Also, I just made a tiny improvement to the iPhone app.
I added a chevron to the variants button to make it clear that it can be tapped.
What do you think?

Capture d’écran 2023-09-29 à 18 56 59

**Comment by wang-li** [comment]
> Also, I just made a tiny improvement to the iPhone app.
I added a chevron to the variants button to make it clear that it can be tapped.
What do you think?

Great idea! 👍 I added a down chevron as well 😉

**Comment by wang-li** [comment]
> Is there a way to highlight the grade more subtly? For example we could align the grade on the right side (and keep the problem name on the left side).

I updated the alignments of the grades ✅ 
In order to remove any circuit color association, I propose to remove the background of the grade and just keep an outline, this should be neutral enough. I avoided using the circuit color as a background, because it would be confusing with the problem number. What do you think about it?

**Comment by nmondollot** [comment]
All right, I like it!

**Review by nmondollot — APPROVED** [review]

**Pull request merged**
